name: Github Actions Demo

on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]

  pull_request:
    branches: [main]

  schedule:
    - cron: '15 06 * * 0'

  workflow_dispatch:
    inputs: 
      environment:
        type: environment
        required: true
        description: "Environment to deploy to"
    
jobs:
  Build: 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Job was triggered by event: ${{ github.event.name }}"
          echo "Branch name: ${{ github.ref }}"
          
      - uses: actions/checkout@v3.3.0

      - name: List files in repo
        run: |
          echo "${{github.repository}} contains:"
          tree


  Test:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: [Build]
    environment: Test
    steps:
      - run: echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: [Build]
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - run: echo "Testing..."
      - run: sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: echo "Step 1 deploying..."
      - run: sleep 10
      - run: echo "Step 2 deploying..."
      - run: sleep 10
      - run: echo "Step 3 deploying..."
      - run: sleep 10
      - run: echo "Step 4 deploying..."
      - run: sleep 10
      - run: echo "Step 5 deploying..."
      - run: sleep 10
