name: Hello World Docker CI

on:
  push:
    branches: [main]
    paths: [hello-world-docker-action/**]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0

      - name: run my own container action
        id: hello-action
        uses: ./.github/actions/hello-world-docker-action
        with:
          who-to-greet: 'Raj'

      - name: output time
        run: echo "The time was ${{ steps.hello-action.outputs.time }} when the action said hello"
